Fix some of the german translation.
LambdAurora/LambDynamicLights pull request #11
Opened 2020-07-21 12:50 UTC by redstonekasi

Changed some of the translations to make more sense.

2020-07-21 13:11 UTC, Sturmlilie commented
Small note: If you wanna be consistent with vanilla, use "Objekte" for "entities". [1]

[1] https://minecraft-de.gamepedia.com/Objekt

2020-07-28 20:44 UTC, AlexanderRitter02 requested changes

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
>    "lambdynlights.option.block_entities": "Blockentitäten",
```suggestion
  "lambdynlights.option.block_entities": "Blockobjekte",
```
This is the German term used in the Minecraft wiki, for consistency: https://minecraft-de.gamepedia.com/Blockobjektdaten

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
>    "lambdynlights.menu.canvas.2": "Dynamische Beleuchtung mit Canvas ist zur Zeit sehr Leistungsbedürftig!",
```suggestion
  "lambdynlights.menu.canvas.2": "Dynamische Beleuchtung mit Canvas ist zur Zeit sehr leistungsbedürftig!",
```
Small spelling correction.

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
>    "lambdynlights.toast.first_time": "Automatisch ausgeschaltet, prüfen Sie die Mod- oder Videoeinstellungen nach!",
1. That must either be:
`"prüfen Sie **in** den Mod- oder Videoeinstellungen nach!"`
or
`"prüfen Sie die Mod- oder Videoeinstellungen!"`
A mix doesn't make sense gramatically.

2. Default **is not** equal to automatic, it is rather `"Standardmäßig"`.

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
>    "lambdynlights.tooltip.block_entities": "Schaltet Blockentitäten dynamische Beleuchtung ein.",
```suggestion
  "lambdynlights.tooltip.block_entities": "Schaltet dynamische Beleuchtung für Blockobjekte ein.",
```
Same as above, term used in Minecraft wiki.
Also correct the word order in the sentence.

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
> +  "lambdynlights.tooltip.creeper_lighting": "Ändert das Verhalten der dynamische Beleuchtung des Creepers\n- %s schaltet dieses aus.\n- %s: konstante Beleuchtung durch explosierende Creepers.\n- %s:
```suggestion
  "lambdynlights.tooltip.creeper_lighting": "Ändert das Verhalten der dynamische Beleuchtung bei Creepern\n- %s schaltet dieses aus.\n- %s: konstante Beleuchtung durch explodierende Creepers.\n- %s: Zunehmende Beleuchtung durch explodierende Creepers.",
```

1. _"des Creepers" -> "bei Creepern"_. The sentence applies to all creepers, not only one. Also sounds better.
2. "Explodieren" is written with a **"d"**: https://www.duden.de/suchen/dudenonline/explodierende

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
>    "lambdynlights.tooltip.mode.1": "Aktiviert dynamische Beleuchtung. Wenn es aktiviert ist wird zB. einem Fackel-haltendem Spieler seine Umgebung beleuchtet.",
```suggestion
  "lambdynlights.tooltip.mode.1": "Aktiviert dynamische Beleuchtung. Wenn aktiv, wird z. B. ein Spieler, der eine Fackel hält, die Umgebung beleuchten."
```
The current translation is a bit rough, improve it and also correct punctuation (comma).

2020-07-28 20:44 UTC, AlexanderRitter02 commented on src/main/resources/assets/lambdynlights/lang/de_de.json
> +  "lambdynlights.tooltip.water_sensitive": "Aktiviert die Wasserempfindlichkeit: einige Gegenstände werden kein Licht im Wasser abgeben."
```suggestion
  "lambdynlights.tooltip.water_sensitive": "Aktiviert die Wasserempfindlichkeit: Einige Gegenstände werden kein Licht im Wasser abgeben."
```
A new sentence after a colon should be capitalized: https://www.duden.de/sprachwissen/rechtschreibregeln/doppelpunkt

2020-07-31 15:14 UTC, merged